services:
  web:
    build: .
    ports: ["8000:8080"]
    environment:
      - FLASK_ENV=production
      - STORAGE_BACKEND=${STORAGE_BACKEND:-minio}
      - MINIO_ENDPOINT=${MINIO_ENDPOINT:-minio:9000}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY:-minioadmin}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY:-minioadmin}
      - MINIO_BUCKET=${MINIO_BUCKET:-mawenhouse}
      - MINIO_SECURE=${MINIO_SECURE:-0}
      - REDIS_URL=redis://redis:6379/0
    depends_on: [redis, minio]
    volumes: [".:/app"]
    restart: unless-stopped
  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes --appendfsync everysec
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
    ports: ["6379:6379"]
    volumes: 
      - redis-data:/data
    restart: unless-stopped
  minio:
    image: minio/minio:RELEASE.2024-01-16T16-07-38Z
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-minioadmin}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-minioadmin}
    ports: ["9000:9000","9001:9001"]
    volumes: 
      - minio-data:/data
    restart: unless-stopped
    

volumes:
  redis-data:
    driver: local
  minio-data:
    driver: local
