from abc import ABC, abstractmethod
class StorageBackend(ABC):
    @abstractmethod
    def get_json(self,key:str):...
    @abstractmethod
    def put_json(self,key:str,data):...
    @abstractmethod
    def get_object(self,key:str)->bytes:...
    @abstractmethod
    def put_object(self,key:str,data:bytes,content_type:str|None=None)->None:...
